# Generated by Django 4.1.7 on 2023-07-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('regis_date', models.DateField()),
                ('institution', models.CharField(max_length=15)),
                ('regis_time', models.TimeField()),
                ('state', models.CharField(max_length=15)),
                ('observation', models.CharField(max_length=50)),
            ],
        ),
    ]
